# Site settings
title: "My Resume" # 站点标题
description: "Welcome to my personal resume website!" # 站点描述
author: "Your Name" # 站点作者

# Build settings
markdown: kramdown # 设置 Markdown 渲染器
theme: minima # 使用 minima 主题

# Site URL (update this with your actual site URL)
url: "https://ssy1895.github.io" # 站点 URL
baseurl: "/my-resume" # 如果你使用了子目录（例如 GitHub Pages 下的子项目），请在这里设置

# Social media links (可选，替换为你的社交媒体链接)
social_links:
  - name: "GitHub"
    url: "https://github.com/ssy1895"
  - name: "LinkedIn"
    url: "https://www.linkedin.com/in/yourname"
  - name: "Twitter"
    url: "https://twitter.com/yourname"

# Navigation
header:
  - text: "Home"
    url: "/"
  - text: "About"
    url: "/about/"
  - text: "Contact"
    url: "/contact/"

# Google Analytics (可选)
# google_analytics: "UA-XXXXXXXXX-X"  # 将此行替换为你的 Google Analytics 跟踪代码

# Posts configuration
# Enable categories and tags for blog posts
posts:
  categories: true
  tags: true

# Enable archive pages (optional, for large blogs)
paginate: 5 # 每页显示的文章数

# Enable pagination for older posts
paginate_path: "/page:num"

# Show last updated date
show_last_updated: true

# Enable disqus comments (可选，如果需要评论功能)
# disqus:
#   shortname: "your-disqus-shortname" # 设置 Disqus 的短名称

# Enable RSS feed (可选，如果你希望提供 RSS 订阅)
feed:
  path: "rss.xml"

# Specify layout for different pages
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post" # 设置博客文章的布局为 'post'
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default" # 设置页面的布局为 'default'

# Include custom styles (optional)
# Uncomment and specify the path to your custom stylesheets if needed
# css:
#   - "assets/css/style.css"

# Enable or disable the sidebar (optional, depending on the theme's layout)
sidebar:
  enable: true

# Include footer settings (optional)
footer:
  copyright: "© 2024 Your Name. All rights reserved."
  powered_by: "Powered by Jekyll & GitHub Pages"

# Enable or disable search functionality (optional, for larger sites)
# search:
#   enable: true

# Show social sharing buttons (optional)
social_sharing: true

# Enable or disable HTTPS (recommended)
# enforce_https: true
